### ISSUE TITLE
May I ask how to solve the problem of missing files?

### ISSUE THREAD

**Issue by Diggle221** [ulterzlw/kitti2bag#1]
Traceback (most recent call last):
  File "/usr/local/bin/kitti2bag", line 11, in <module>
    load_entry_point('kitti2bag==1.5', 'console_scripts', 'kitti2bag')()
  File "build/bdist.linux-x86_64/egg/kitti2bag/__main__.py", line 5, in main
  File "build/bdist.linux-x86_64/egg/kitti2bag/kitti2bag.py", line 378, in run_kitti2bag
  File "/usr/local/lib/python2.7/dist-packages/pykitti/odometry.py", line 33, in __init__
    self._load_calib()
  File "/usr/local/lib/python2.7/dist-packages/pykitti/odometry.py", line 147, in _load_calib
    filedata = utils.read_calib_file(calib_filepath)
  File "/usr/local/lib/python2.7/dist-packages/pykitti/utils.py", line 72, in read_calib_file
    with open(filepath, 'r') as f:
IOError: [Errno 2] No such file or directory: './dataset/sequences/04/calib.txt'

I'm sure the file exists

**Comment by ulterzlw** [comment]
Did you `unzip data_odometry_calib.zip`?
And the folder `dataset/` should be organized as follow
```bash
├── dataset
│   ├── poses
│   │   ├── 00.txt
│   │   ├── ...
│   ├── sequences
│   │   ├── 00
│   │   │   ├── calib.txt
│   │   │   ├── times.txt
│   │   │   ├── image_0
│   │   │   │   ├── ...
│   │   │   ├── image_1
│   │   │   │   ├── ...
│   │   │   ├── image_2
│   │   │   │   ├── ...
│   │   │   ├── image_3
│   │   │   │   ├── ...
│   │   │   ├── velodyne
│   │   │   │   ├── ...
│   │   ├── ...
```
