### ISSUE TITLE
ImportError: Entry point ('console_scripts', 'kitti2bag') not found

### ISSUE THREAD

**Issue by FishInWave** [ulterzlw/kitti2bag#3]
hi @ulterzlw ，
When I use your fork, an error occurs. 
I have done every steps in your readme. Is there anything I missed?
```
$ kitti2bag -t 2011_09_26 -r 0002 raw_sync .
Traceback (most recent call last):
  File "/usr/local/bin/kitti2bag", line 11, in <module>
    load_entry_point('kitti2bag==1.5', 'console_scripts', 'kitti2bag')()
  File "/home/xyw/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/xyw/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2851, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('console_scripts', 'kitti2bag') not found
```

**Comment by FishInWave** [comment]
I just got it to work by uninstalling kitti2bag by `python -m pip uninstall kitti2bag` and reinstall it referring to [Installing from source results in ModuleNotFoundError
#41](https://github.com/tomas789/kitti2bag/issues/41)
